apiVersion: v2
name: ws-oidc-provider
description: Workspace OIDC provider with Redis subchart
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 18.7.1
    repository: https://charts.bitnami.com/bitnami