workspaceOidcProvider:
  namespace: "ws-oidc-provider-ns"
  deployment:
    name: "ws-oidc-provider-deployment"
    appName: "ws-oidc-provider"
    replicaCount: 1
    image:
      repository: "localhost/redis-app"
      tag: "latest"
      pullPolicy: "Never"
    containers:
      name: "ws-oidc-provider"
    env:
      jwtSecretKey: "your_jwt_secret_key"
      dbHost: "127.0.0.1"
      dbPort: "3306"
      dbUser: "root"
      dbPass: "root"
      dbName: "oidc_provider"
      dbDialect: "mysql"
      oidcUrl: "https://authDB_USER.businesseye.dev:3000/oidc"
      workspaceUrl: "https://magic.businesseye.dev"

      # ðŸ‘‡ Redis URL will be dynamically rendered using the Helm release name
      redisUrl: "redis://:dev-redis-pass@ws-oidc-provider-redis-service:6378/0"
      redisTtlSeconds: "3600"

  service:
    name: "ws-oidc-provider-service"
    appName: "ws-oidc-provider"
    port: 81
    containerPort: 3000
    nodePort: 30080