apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workspaceOidcProvider.service.name }}
  namespace: {{ .Values.workspaceOidcProvider.namespace }}
spec:
  selector:
    app: {{.Values.workspaceOidcProvider.service.appName }}
  ports:
      - port: {{ .Values.workspaceOidcProvider.service.port }}
        targetPort: {{ .Values.workspaceOidcProvider.service.containerPort }}
        nodePort: {{  .Values.workspaceOidcProvider.service.nodePort }}
  type: NodePort
