apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
spec:
  type: NodePort
  selector:
    app: '{{ .Release.Name }}'
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
