apiVersion: v1
kind: Service
metadata:
    name: ws-oidc-provider-redis-service
    namespace: {{ .Values.namespace }}
spec:
    selector:
        app: ws-oidc-provider-redis
    type: ClusterIP
    ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}